version: '3'

networks:
  default:

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: gio_platform_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/gio-selfsigned.crt:/etc/ssl/certs/gio-selfsigned.crt
      - ./nginx/ssl/gio-selfsigned.key:/etc/ssl/private/gio-selfsigned.key
      - ./nginx/ssl/gio.pem:/etc/ssl/certs/gio.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apim_gateway
      - apim_portal
      - apim_management
      # - am_gateway
      # - am_management
      # - am_webui

  mongodb:
    image: mongo:3.4
    restart: always
    container_name: gio_platform_mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=gravitee
    volumes:
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./data/mongo:/data/db
      - ./logs/mongodb:/var/log/mongodb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: gio_platform_elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
    ulimits:
      nofile: 65536
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/var/log/elasticsearch

  apim_gateway:
    image: graviteeio/gateway:latest
    container_name: gio_platform_apim_gateway
    restart: always
    volumes:
      - ./logs/apim-gateway:/opt/graviteeio-gateway/logs
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
    depends_on:
      - mongodb
      - elasticsearch

  apim_portal:
    image: graviteeio/management-ui:latest
    container_name: gio_platform_apim_portal
    restart: always
    volumes:
      - ./gio_apim/portal/constants.json:/var/www/html/constants.json.template
    depends_on:
      - apim_management

  apim_management:
    image: graviteeio/management-api:latest
    container_name: gio_platform_apim_mgmt_api
    restart: always
    volumes:
      - ./logs/apim-management-api:/opt/graviteeio-management-api/logs
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
      - gravitee_jwt_cookiepath=/apim/management
      - gravitee_jwt_cookiesecure=true
      - gravitee_security_providers_2_type=oauth2
      - gravitee_security_providers_2_clientId=apim_portal
      - gravitee_security_providers_2_clientSecret=b90efce4-1ab2-49d9-8efc-e41ab2a9d99e
      - gravitee_security_providers_2_tokenEndpoint=http://am_gateway:8092/portal/oauth/token
      - gravitee_security_providers_2_userInfoEndpoint=http://am_gateway:8092/portal/oidc/userinfo
      - gravitee_security_providers_2_accessTokenProperty=access_token
      - gravitee_security_providers_2_authorizationHeader=Bearer %s
      - gravitee_security_providers_2_mapping_id=sub
      - gravitee_security_providers_2_mapping_email=email
      - gravitee_security_providers_2_mapping_lastname=family_name
      - gravitee_security_providers_2_mapping_firstname=given_name
      - gravitee_security_providers_2_mapping_picture=avatar_url
    depends_on:
      - mongodb
      - elasticsearch

  # am_gateway:
  #   image: graviteeio/am-gateway:2
  #   container_name: gio_platform_am_gateway
  #   restart: always
  #   volumes:
  #     - ./logs/am-gateway:/opt/graviteeio-am-gateway/logs
  #   environment:
  #     - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
  #     - gravitee_oauth2_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
  #   depends_on:
  #     - mongodb

  # am_management:
  #   image: graviteeio/am-management-api:2
  #   container_name: gio_platform_am_management
  #   restart: always
  #   volumes:
  #     - ./logs/am-management-api:/opt/graviteeio-am-management-api/logs
  #   environment:
  #     - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
  #     - gravitee_oauth2_mongodb_uri=mongodb://mongodb:27017/gravitee-am?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
  #     - gravitee_jwt_cookiepath=/am/management
  #     - gravitee_jwt_cookiesecure=true
  #   depends_on:
  #     - mongodb

  # am_webui:
  #   image: graviteeio/am-management-ui:2
  #   container_name: gio_platform_am_webui
  #   restart: always
  #   environment:
  #     - MGMT_API_URL=https:\/\/localhost\/am\/
  #     - MGMT_UI_URL=https:\/\/localhost\/am\/ui\/
  #   volumes:
  #     - ./logs/am-webui:/var/log/nginx
  #   depends_on:
  #     - am_management
